#!/usr/bin/env python3
"""Convert a recorded session's controller.jsonl into a `pokebot run --script`.

The script reproduces the recording on the stepped in-process emulator: for
each command it waits the frames the recorder observed since the previous
command (`after_frame_id` deltas), then issues the command. With the same
cartridge save, replaying the script lands on the same frames as the
recording (the stepped emulator is deterministic).

Usage:
    to_script.py SESSION_DIR_OR_CONTROLLER_JSONL [-o OUT] [--until-frame N]
                 [--append FILE] [--no-tail]

    --until-frame N  drop commands issued after frame N (the script then
                     waits up to frame N, so it ends on frame N)
    --append FILE    append FILE's lines (e.g. probe inputs and screenshots)
    --no-tail        do not wait for the frames the recording observed after
                     its last command (by default the script ends on the
                     recording's last frame, read from frames.jsonl)

Frame numbering: `after_frame_id` is the last frame observed when the command
was issued (null: none yet). Frame ids start at 0, so a first command after
frame k needs k + 1 observed frames.
"""

import argparse
import json
import sys
from pathlib import Path


def fmt_duration(d):
    secs, nanos = d["secs"], d["nanos"]
    total_ns = secs * 1_000_000_000 + nanos
    if total_ns % 1_000_000 == 0:
        return f"{total_ns // 1_000_000}ms"
    return f"{secs}.{nanos:09d}s"


def fmt_buttons(buttons):
    return "+".join(buttons) if buttons else "none"


def fmt_command(command):
    if command == "Neutral":
        return "neutral"
    (kind, body), = command.items()
    if kind == "Press":
        return f"press {body}"
    if kind == "Chord":
        return f"chord {fmt_buttons(body)}"
    if kind == "Hold":
        return f"hold {fmt_buttons(body['buttons'])} {fmt_duration(body['duration'])}"
    if kind == "Sequence":
        parts = [f"{fmt_buttons(t['buttons'])}:{fmt_duration(t['duration'])}" for t in body]
        return "sequence " + " ".join(parts)
    raise ValueError(f"unknown command {command!r}")


def frames_through(frame_id):
    """Frames observed once frame `frame_id` has been seen (None: none)."""
    return 0 if frame_id is None else frame_id + 1


def last_frame_id(frames_jsonl):
    last = None
    with open(frames_jsonl) as f:
        for line in f:
            if line.strip():
                last = json.loads(line)["frame_id"]
    return last


def convert(records, until_frame=None, tail_frame=None):
    lines = []
    seen = 0  # frames observed so far by the replay
    for rec in records:
        after = rec["after_frame_id"]
        if until_frame is not None and after is not None and after > until_frame:
            break
        target = frames_through(after)
        if target > seen:
            lines.append(f"wait {target - seen}")
            seen = target
        lines.append(fmt_command(rec["command"]))
    end = until_frame if until_frame is not None else tail_frame
    if end is not None and frames_through(end) > seen:
        lines.append(f"wait {frames_through(end) - seen}")
    return lines


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("session", type=Path, help="session dir or controller.jsonl")
    ap.add_argument("-o", "--output", type=Path, help="script path (default: stdout)")
    ap.add_argument("--until-frame", type=int)
    ap.add_argument("--append", type=Path, action="append", default=[])
    ap.add_argument("--no-tail", action="store_true")
    args = ap.parse_args()

    path = args.session
    controller = path / "controller.jsonl" if path.is_dir() else path
    frames = controller.parent / "frames.jsonl"
    with open(controller) as f:
        records = [json.loads(line) for line in f if line.strip()]
    tail = None
    if not args.no_tail and args.until_frame is None and frames.exists():
        tail = last_frame_id(frames)

    out = [f"# generated by tools/probe/to_script.py from {controller}"]
    out += convert(records, args.until_frame, tail)
    for extra in args.append:
        out.append(f"# --- appended from {extra}")
        out += extra.read_text().splitlines()
    text = "\n".join(out) + "\n"
    if args.output:
        args.output.write_text(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
