[package]
name = "pokebot-planner"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
pokebot-core.workspace = true
pokebot-gamedata.workspace = true
pokebot-state.workspace = true
pokebot-world.workspace = true
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[dev-dependencies]
pokebot-gamedata = { path = "../gamedata" }
